[env]
KMP_DUPLICATE_LIB_OK = true
RENV_CONFIG_USER_PROFILE = true

# Add Anthropic Variables
ANTHROPIC_AUTH_TOKEN = "ollama"
ANTHROPIC_API_KEY = ""
ANTHROPIC_BASE_URL = "http://localhost:11434"

# Extend Ollama context window
OLLAMA_CONTEXT_LENGTH = 64000

[tools]
python = "3.10"
